import { Button, ListView, HorizontalBox } from "std-widgets.slint";
import { UserData, UserList } from "user.slint";
import { EntryData, Timeline } from "timeline.slint";

component MyButton inherits Rectangle {
    width: 200px;
    height: 100px;
    
    callback clicked <=> button.clicked;
    button := Button {
        width: parent.width;
        height: parent.height;
        text: "Update";
    }
}

export component MainWindow inherits Window {
    min-height: 600px;
    min-width: 950px;
    preferred-height: 700px;
    preferred-width: 1200px;

    in-out property <[EntryData]> events;
    in-out property <[UserData]> users;
    callback update <=> button.clicked;


    HorizontalBox {
        VerticalLayout {
            spacing: 3px;

            Text { text: "Users"; }
            UserList { model: users; }
        }

        VerticalLayout {
            spacing: 3px;

            Text { text: "Events"; }
            Timeline { model: events; }
        }

        VerticalLayout {
            alignment: end;

            button := MyButton {}
        }
    }
}
