import { ListView, HorizontalBox, GroupBox } from "std-widgets.slint";

export struct EntryData {
    date: string,
    open: bool,
    events: [string],
}

component Entry inherits Rectangle {
    in-out property <EntryData> model;
    in-out property <int> font-size: 20;

    VerticalLayout {
        alignment: start;
        spacing: 2px;

        TouchArea {
            clicked => { model.open = !model.open; }
            
            HorizontalLayout {
                alignment: start;
                spacing: 5px;

                Text {
                    text: (model.open ? "⊟" : "⊞");
                    vertical-alignment: center;
                    font-size: root.font-size*1px;
                    y:  - 0.2 * self.font-size;
                }
                
                Text {
                    vertical-alignment: center;
                    font-size: root.font-size*1px;
                    text: model.date;
                }
            }
        }
        
        if model.open : ListView {
            for dep in model.events : HorizontalLayout {
                spacing: 10px;

                Rectangle { width: 20px; }
                Text {
                    text: dep;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
            }
        }
    }
}

export component Timeline inherits ListView {    
    in property <[EntryData]> model;
    for event in model : HorizontalBox {
        Entry {
            model: event;
        }
    }
}