import { ListView, HorizontalBox } from "std-widgets.slint";

export struct UserData {
    id: string,
    name: string,
    picture: image,
    events: int,
}

export component User inherits Rectangle {
    in property <UserData> model;
    callback clicked <=> area.clicked;

    area := TouchArea {
        HorizontalLayout {
            spacing: 10px;
            alignment: start;
            padding: 6px;

            Rectangle {
                width: 40px;
                height: 40px;
                clip: true;
                border-radius: self.width/2;

                Image {
                    width: parent.width;
                    height: parent.height;
                    source: model.picture;
                }
            }

            VerticalLayout {
                alignment: center;
                spacing: 5px;

                username := Text {
                    width: 100px;
                    text: model.name;
                }

                Text {
                    text: model.events + " Events";
                    font-size: 10px;
                }
            }
        }
    }
}

export component UserList inherits ListView {
    width: 200px;
    
    callback clicked(string);
    in property <[UserData]> model;
    for user in model : HorizontalBox {
        User {
            model: user;
            clicked => { root.clicked(user.id) }
        }
    }
}